server:
  port: 8005 # 端口号

spring:
  # 应用名称
  application:
    name: hystrix-payment-service # 服务名称
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/cloud?useSSL=false&serverTimezone=UTC
    username: root
    password: 6210

  # 是否支持热部署
  devtools:
    restart:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka # 单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版
  instance:
    instance-id: payment8005
    prefer-ip-address: true
    # eureka客户端想服务端发动心跳的时间间隔，单位为秒（默认是30秒）。开发的时候可以设置小一些，以保证服务关闭后注册中心及时剔除服务
    lease-renewal-interval-in-seconds: 20
    # eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒）。开发时候设置小一些
    lease-expiration-duration-in-seconds: 20

mybatis:
  mapperLocations: classpath:mapper/*.xml #mapper文件
  type-aliases-package: cn.chen.cloud.entity  #所有entity别名所在包
