server:
  port: 80

spring:
  application:
    name: zookeeper-consumer-order
  cloud:
    zookeeper:
      connect-string: 192.168.120.131:2181 #zk注册中心地址
zk:
  server:
    url: http://cloud-provider-payment
