spring:
  application:
    name: CLOUD-PROVIDER-PAYMENT
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/cloud?useSSL=false&serverTimezone=UTC
    username: root
    password: 6210
    devtools:
      restart:
        enabled: true #是否支持热部署
server:
  port: 8002
eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka/ # 入驻地址

